# Generated by Django 6.0.1 on 2026-02-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a new book'), ('can_change_book', 'Can edit/modify book information'), ('can_delete_book', 'Can delete a book')]},
        ),
    ]
